### PR TITLE
add animation in navbar and button

### PR DESCRIPTION
**Pull request by kratigoyal34**

### CODE REVIEW

**Comment by ankman007** [comment]
@kratigoyal34 Please provide proper description along with screenshots of the changes you've made. Also, link to the issue of the problem you are trying to solve (if any).

**Comment by kratigoyal34** [comment]
could you please tell where I have to paste the screenshot, As I have the screenshot but where I have to paste it.

**Comment by kratigoyal34** [comment]
@ankman007 could you please tell me where I have to paste the screenshot as I have the screenshot but don't know where to paste.

**Comment by kratigoyal34** [comment]
@ankman007 when we hover on the nav-item the underline will not just simply form but also animate.

Screenshot 2023-10-26 223642

Screenshot 2023-10-27 124106



and when we hover on the button it expands so give a feeling as it is a different link.

Screenshot 2023-10-26 223715

**Comment by ankman007** [comment]
@kratigoyal34 all seems good.

**Pull request merged**
